/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CatCoin } from './CatCoin.js';
export * as factories from './factories/index.js';
export { CatCoin__factory } from './factories/CatCoin__factory.js';